
#pragma once

#include "../utt_cases/utt/utt_self_test.hpp"
#include "../utt_cases/utils/sweeper_test.hpp"
#include "../utt_cases/sync/single_entry_test.hpp"
#include "../utt_cases/envs/nowadays_test.hpp"
#include "../utt_cases/utils/auto_removed_folder_test.hpp"
#include "../utt_cases/utils/uuid_test.hpp"
#include "../utt_cases/sync/spin_wait_test.hpp"
#include "../utt_cases/sync/reset_event_test.hpp"
#include "../utt_cases/formation/concurrent/slimqless_single_test.hpp"
#include "../utt_cases/formation/concurrent/slimqless_test.hpp"
#include "../utt_cases/formation/concurrent/slimqless2_test.hpp"
#include "../utt_cases/formation/concurrent/qless_test.hpp"
#include "../utt_cases/utils/pattern_matcher_test.hpp"
#include "../utt_cases/utt/utt_specific_test.hpp"
#include "../utt_cases/utt/utt_failure_test.hpp"
#include "../utt_cases/threadpool/queue_runner_test.hpp"
#include "../utt_cases/envs/envs_test.hpp"
#include "../utt_cases/utils/str_contains_test.hpp"
#include "../utt_cases/utils/timing_counter_test.hpp"
#include "../utt_cases/formation/concurrent/slimqless_perf_test.hpp"
#include "../utt_cases/formation/concurrent/slimqless2_perf_test.hpp"
#include "../utt_cases/formation/concurrent/qless3_test.hpp"
#include "../utt_cases/formation/concurrent/qless3_perf_test.hpp"
#include "../utt_cases/sync/exclusive_container_test.hpp"
#include "../utt_cases/sync/atomic_shared_ptr_test.hpp"
#include "../utt_cases/utils/cd_object_test.hpp"
#include "../utt_cases/threadpool/queue_runner_repeat_test.hpp"
#include "../utt_cases/threadpool/queue_runner_once_test.hpp"
#include "../utt_cases/threadpool/threadpool_test.hpp"
#include "../utt_cases/utils/recursive_deleter_test.hpp"
#include "../utt_cases/formation/fixed_stack_test.hpp"
#include "../utt_cases/utils/convertor_test.hpp"
#include "../utt_cases/utils/call_stack_test.hpp"
#include "../utt_cases/threadpool/stopwatch_test.hpp"

